# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba62848511a8e2c1b869ce085f4511829fe21b693aa41dbeebb204e7fab814d9d3cf8e5d4af26b439b317502448db9777d0b89b3dd334f6d67fdef545510066b

test:
  secret_key_base: 501593f45414e8a362fd490d7eebd128dbc66d873f45e947dd13382b2a2181acbdb7e72a2995608a5a87bd4c676ca94c786e819188f44d8c3e183844f9c13722

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
